version: "1.0"
devices:
    - id: 9142d4e8-ba92-4c4d-8c59-c20c3eec3144
      name: PLC-001
      protocol: opcua
      enabled: true
      uns_prefix: ghent/prd/line1
      poll_interval: 10s
      connection:
        host: nexus-opcua-sim
        port: 4840
        timeout: 10s
        retry_count: 0
        retry_delay: 0s
        slave_id: 0
        opc_endpoint_url: opc.tcp://nexus-opcua-sim:4840
        opc_security_policy: None
        opc_security_mode: None
        opc_auth_mode: anonymous
        opc_username: ""
        opc_password: ""
        opc_cert_file: ""
        opc_key_file: ""
        opc_server_cert_file: ""
        opc_insecure_skip_verify: false
        opc_auto_select_endpoint: false
        opc_application_name: ""
        opc_application_uri: ""
        opc_use_subscriptions: false
        opc_publish_interval: ""
        opc_sampling_interval: ""
        s7_rack: 0
        s7_slot: 0
      tags:
        - id: 53047175-540c-4ce6-838c-d14cb14abac2
          name: temp
          data_type: float32
          scale_factor: 1
          topic_suffix: temp
          deadband_type: none
          enabled: true
          access_mode: read
          byte_order: big_endian
          opc_node_id: ns=2;s=Demo.Temperature
        - id: a74502d5-a180-4cba-ab1c-9442171dd5fa
          name: switch
          data_type: bool
          scale_factor: 1
          topic_suffix: switch
          deadband_type: none
          enabled: true
          access_mode: readwrite
          byte_order: big_endian
          opc_node_id: ns=2;s=Demo.Switch
